### ISSUE TITLE
LBA mode

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-db#3]

**Comment by maxux** [comment]
Is this really needed ? I don't get the point.
Let imagine we use fixed 4 KB blocks, using 2 bytes for the fileid would gives 2 bytes for the position, which will put the limit at ~256 MB of data. I don't think the 4 bytes id is useful.

**EDIT:** actually, since we split datafile per 256 MB, this is okay.

**Comment by maxux** [comment]
The original 4 KB block mode will not be implemented, but a « LBA » mode will replace it.
This mode is made to handle zdb in a better way when it's used as block driver backend for storage.

Idea is to use a mapping file between LBA ID and position (like direct mode).
