### ISSUE TITLE
Implement delete namespace

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/0-db#33]
We need a command to delete namespace

**Comment by maxux** [comment]
I'll implement a first naive version, in order to have it working at least.

The initial version will need to walk over all the existing keys to delete keys attached to that namespace.
This can cause a long lockdown of the process depending on how many keys are in memory.

When the allocation of the index will be reviewed, this time will be reduced.

**Comment by maxux** [comment]
Side effects and security:
- You won't be able to remove a namespace if you're attached to it
- Any clients connected to that namespace will be disconnected at their next command
